chore: add diagrams showing update processes
jenkins-infra/update-center2 pull request #453
Opened 2020-10-02 13:49 UTC by garethjevans

2020-10-02 17:25 UTC, MarkEWaite approved these changes
That looks great!  Thanks very much

2020-10-02 18:07 UTC, daniel-beck requested changes
Regarding the chosen format: Given how trivial these flows are, please provide a textual version. Even if you did provide the source files, this is much more cumbersome to update, impossible to search, and less accessible, as image files.

Beyond that, the location you add these does not make sense. Granted, the docs in this repo are a bit distributed, but there are better locations: Perhaps some of this can be integrated into https://github.com/jenkins-infra/update-center2/blob/master/site/LAYOUT.md#top-level-htaccess-file (for the mirror redirection stuff) and https://github.com/jenkins-infra/update-center2/blob/master/site/LAYOUT.md#known-consumers expanded to explain how Jenkins consumes this.

In general though, I'm not a big fan of putting documentation outside the context it applies to; so exactly where mirrorbits redirects to, or even what sort of mirror infra exists, has no real reason to be in this repo. It's just going to get stale.

2020-10-02 18:07 UTC, daniel-beck commented on site/README.md
> +### What happens when 'Update Now' is pressed?
Third level header directly below a first level header makes no sense.

Beyond formatting, this is also unrelated to anything else going on in this document.

2021-03-11 19:52 UTC, garethjevans commented
abandoning

2021-03-11 19:52 UTC, closed without merging