Remove wiki urls by rewriting them to github blobs
jenkins-infra/update-center2 pull request #548
Opened 2021-09-16 03:17 UTC by halkeye

cc @daniel-beck @zbynek

2021-09-18 17:49 UTC, daniel-beck commented
Thanks! Are there plans to create the pages that are currently missing?

```
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/ColumnsPlugin/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/alauda-devops-credentials-provider/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/alauda-devops-pipeline/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/alauda-kubernetes-support/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/aqua-microscanner/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/aqua-serverless/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/autocomplete-parameter/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/aws-yum-parameter/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/behave-testresults-publisher/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/database-drizzle/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/devstack/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/dlisting-cov/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/dynatrace-dashboard/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/event-announcer/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/flexteam/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/h2-api/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/humbug/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/humio/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/ibm-continuous-release/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/ibm-security-appscansource-scanner/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/ikachan/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/jenkinspider/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/jna-posix-api/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/jnr-posix-api/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/jprt/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/jwt-support/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/kubesphere-token-auth/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/metrics-datadog/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/multi-branch-priority-sorter/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/mysql-api/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/network-monitor/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/non-dynamic-hello-world/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/pipeline-deploymon/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/pipeline-huaweicloud-plugin/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/pipeline-restful-api/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/pipeline-timeline/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/qc/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/rallyBuild/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/sealights/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/sourcemonitor/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/suite-test-groups-publisher/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/webhook-eventsource/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/working-hours/README.md
https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/wso2id-oauth/README.md

2021-09-18 18:09 UTC, halkeye commented
No concrete plans. Those are very hard to find.
For example https://github.com/jenkinsci/aqua-microscanner-plugin links to https://wiki.jenkins-ci.org/display/JENKINS/Aqua+MicroScanner+Plugin

```
 Page Not Found

We can't find that page. This could be because:

    The page doesn't exist.
    The page exists, but you don't have view permission for that space.

Site Search
Go to

    Site Homepage
    Your Dashboard
```

Web archive doesn't either

http://web.archive.org/web/*/https://wiki.jenkins-ci.org/display/JENKINS/Aqua+MicroScanner+Plugin

So each of those 2 dozen plugins would have to have a lot of manual digging around, and since they didn't work before, i'm not really concerned about this breaking things.

2021-09-18 18:13 UTC, zbynek commented
@halkeye @daniel-beck should we add an override for those to point to their GitHub repo? That can't make things worse... :shrug: I can create a follow-up PR for that.

2021-09-18 18:14 UTC, halkeye commented
I originally pulled the list exported by update center, so if they pointed to the right place I grabbed them - https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/export.js#L39

> should we add an override for those to point to their GitHub repo? That can't make things worse... 🤷 I can create a follow-up PR for that.

🤦 I just realized as I was clicking around, https://github.com/jenkinsci/aqua-microscanner-plugin has a readme. I think the overrides are a good idea

2021-09-18 18:15 UTC, daniel-beck commented
@zbynek Ideally we'd file PRs first for such plugins, at least the ones somewhat actively maintained. Overrides are useful in the short term, but carrying them indefinitely is something we should try to not do.

2021-09-18 18:20 UTC, daniel-beck commented
@halkeye Can you access wiki page rename information, or is that something the exporter already supported? Or do we have a list of all wiki pages to look through for typo'ed / similarly named pages?

(Obviously the ROI here is quickly reached, so we shouldn't overdo it with the manual work.)

<details>
<summary>Affected plugins by popularity</summary>

```
1 dlisting-cov
3 non-dynamic-hello-world
4 humio
5 event-announcer
5 ikachan
6 flexteam
9 devstack
11 jenkinspider
15 suite-test-groups-publisher
17 ibm-continuous-release
18 jnr-posix-api
19 jprt
23 jna-posix-api
24 wso2id-oauth
33 sealights
34 alauda-devops-credentials-provider
35 humbug
36 kubesphere-token-auth
44 alauda-devops-pipeline
48 aqua-serverless
53 rallyBuild
61 ColumnsPlugin
77 jwt-support
79 alauda-kubernetes-support
85 pipeline-huaweicloud-plugin
108 ibm-security-appscansource-scanner
114 working-hours
133 database-drizzle
139 multi-branch-priority-sorter
149 aws-yum-parameter
184 behave-testresults-publisher
205 webhook-eventsource
218 dynatrace-dashboard
238 aqua-microscanner
245 qc
268 autocomplete-parameter
335 metrics-datadog
351 sourcemonitor
373 network-monitor
503 mysql-api
512 pipeline-deploymon
663 pipeline-restful-api
2546 pipeline-timeline
24003 h2-api
```

</details>

2021-09-18 18:26 UTC, zbynek commented
PR for h2-api was merged https://github.com/jenkinsci/h2-api-plugin/pull/2 by @cyrille-leclerc, pipeliine-timeline was updated here https://github.com/jenkinsci/pipeline-timeline-plugin/commit/74bd51eace45008ebb4f3609f71bf0753dec8658, pipeline-restful-api here https://github.com/jenkinsci/pipeline-restful-api-plugin/commit/ed72eaa6ffadc4eb6f707e295e5172b5e92c99cd -- none of them released

2021-09-18 19:13 UTC, halkeye commented
> @halkeye Can you access wiki page rename information, or is that something the exporter already supported? Or do we have a list of all wiki pages to look through for typo'ed / similarly named pages?

I have access to an offline copy and db dump. Its very slow. Lots of pages don't work cause of hostname rename (localhost vs wiki.jenkins). 

I'll admit after 3 years to fix it, these are all ones that didn't bother to do it. I won't shed a tear if they stay broken.

I can try and figure out more when I get back from giving blood. I'll probably import the sql into my homelab and see what i can't find out from raw sql

2021-09-21 01:51 UTC, halkeye commented
anything else I need to do to get this merged?

On Sat, Sep 18, 2021 at 11:27 AM Zbynek Konecny ***@***.***>
wrote:

> PR for h2-api was merged jenkinsci/h2-api-plugin#2
> <https://github.com/jenkinsci/h2-api-plugin/pull/2> by @cyrille-leclerc
> <https://github.com/cyrille-leclerc>, pipeliine-timeline was updated here
> ***@***.***
> <https://github.com/jenkinsci/pipeline-timeline-plugin/commit/74bd51eace45008ebb4f3609f71bf0753dec8658>,
> pipeline-restful-api here ***@***.***
> <https://github.com/jenkinsci/pipeline-restful-api-plugin/commit/ed72eaa6ffadc4eb6f707e295e5172b5e92c99cd>
> -- none of them released
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jenkins-infra/update-center2/pull/548#issuecomment-922351913>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA24B5I6GETU62JKRA7FLLUCTKXTANCNFSM5EDYZC7A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-21 06:35 UTC, daniel-beck commented
No, just waiting for me to have some time, no later than the weekend. How does this currently impact users? Since the site special-cases this already, I didn't get the impression this was urgent.

2021-09-21 06:36 UTC, halkeye commented
Nope. Plugin site has already been patched, I thought I was the blocker so wanted to check in before i archived the email

2021-09-21 14:25 UTC, yJunS requested changes

2021-09-21 14:25 UTC, yJunS commented on src/main/java/io/jenkins/update_center/HPI.java
> +                url = url.replace("https://wiki.jenkins-ci.org", "https://wiki.jenkins.io");
The two lines of code are duplicated

2021-09-21 15:15 UTC, yJunS commented on src/main/java/io/jenkins/update_center/HPI.java
> +                url = url.replace("https://wiki.jenkins-ci.org", "https://wiki.jenkins.io");
`url = url.replace("http://wiki.jenkins-ci.org", "https://wiki.jenkins.io");` 
->
`url = url.replaceAll("(http|https)://wiki.jenkins-ci.org", "https://wiki.jenkins.io");`

2023-09-15 11:21 UTC, lemeurherve commented on src/main/java/io/jenkins/update_center/HPI.java
> +                }
```suggestion
```

Since this PR the wiki service has been restored, no need to redirect to github blobs.

2023-09-27 15:19 UTC, closed without merging