Unsuspend publish-over-ssh since 1.24
jenkins-infra/update-center2 pull request #572
Opened 2022-02-23 08:15 UTC by Wadeck

FYI @gmcdonald @olamy 

Corrections:
- SECURITY-2287, https://github.com/jenkinsci/publish-over-ssh-plugin/pull/50 and https://github.com/jenkinsci/publish-over-ssh-plugin/pull/59
- SECURITY-2290, https://github.com/jenkinsci/publish-over-ssh-plugin/pull/51 and https://github.com/jenkinsci/publish-over-ssh-plugin/pull/58
- SECURITY-2291, https://github.com/jenkinsci/publish-over-ssh-plugin/pull/52
- SECURITY-2307, https://github.com/jenkinsci/publish-over-ssh-plugin/pull/54

Fix version with the fixes: 1.24

2022-02-23 08:36 UTC, daniel-beck commented on resources/artifact-ignores.properties
> +# fixes were proposed since publish-over-ssh-1.24
```suggestion
```

No need to spam the suspension list here.

2022-02-23 08:37 UTC, daniel-beck requested changes
This also needs to update warnings regexes.

2022-02-24 17:01 UTC, timja approved these changes

2022-02-24 18:19 UTC, daniel-beck commented on resources/artifact-ignores.properties
> +# publish-over-ssh => fixes were proposed since publish-over-ssh-1.24, adjust warnings
```suggestion
```

This is what commit history is for.

2022-02-24 20:47 UTC, Wadeck commented
Adjusted using the feedbacks received, merging.

2022-02-24 20:47 UTC, merged