Deprecate bmc-rpd-plugin
jenkins-infra/update-center2 pull request #597
Opened 2022-05-30 12:25 UTC by janfaracik

The way form validation works in Jenkins is changing as part of https://github.com/jenkinsci/jenkins/pull/6460, 'bmc-rpd-plugin' uses custom logic in this area and as such won't work when 6460 is merged. 

Due to the plugins age and inactivity (six years) and that it has an active security warning it's been decided to deprecate the plugin.

2022-05-30 17:52 UTC, basil approved these changes

2022-05-31 07:28 UTC, daniel-beck requested changes

2022-05-31 07:28 UTC, daniel-beck commented on resources/deprecations.properties
> +bmc-rpd-plugin = https://github.com/jenkins-infra/update-center2/pull/597
```suggestion
bmc-rpd = https://github.com/jenkins-infra/update-center2/pull/597
```

See URL: https://plugins.jenkins.io/bmc-rpd/

2022-05-31 08:19 UTC, daniel-beck approved these changes

2022-05-31 08:19 UTC, daniel-beck commented
On-holding until the core fix is out. We should also link to the changelog in the PR comment once that has the change.

2022-06-26 14:06 UTC, timja commented on resources/deprecations.properties
> +bmc-rpd = https://github.com/jenkins-infra/update-center2/pull/597
```suggestion
bmc-rpd = https://www.jenkins.io/changelog/#v2.355
```

2022-06-26 14:07 UTC, timja approved these changes

2022-06-26 14:07 UTC, timja commented on resources/deprecations.properties
> +bmc-rpd = https://www.jenkins.io/changelog/#v2.355
```suggestion
bmc-rpd = https://github.com/jenkins-infra/update-center2/pull/597
```

2022-06-26 14:08 UTC, merged

2022-06-27 08:34 UTC, daniel-beck commented
The changelog entry is completely useless to users, why the change?

2022-06-27 08:42 UTC, timja commented
I changed it back as I realised that too, I was confused by your comment then realised you just wanted it in the body