Switch cache to SHA-256
jenkins-infra/update-center2 pull request #605
Opened 2022-06-24 13:35 UTC by jglick

Fixes https://github.com/jenkins-infra/helpdesk/issues/1968. **Untested.**

2022-06-24 14:50 UTC, dduportal requested changes
To be tested outside before merging: I'm blocking to avoid any accidental merge (ref. https://github.com/jenkins-infra/helpdesk/issues/3019#issuecomment-1165649887)

2022-06-24 14:55 UTC, jglick commented
Note that this could easily be amended to _read_ cache files from the old location as a fallback but only ever _write_ them to the new location. That would allow you to start running it immediately because your cache would already be 99% complete.

2022-06-26 11:13 UTC, dduportal commented
Manual test of this PR in progress:

- Where: trusted agent, as user `jenkins`, in a screen named `pr-uc-605-sha256cache`, in `/home/jenkins/update_center` which a copy of the original job's workspace
- How: 
  1. Cloned locally the PR under the a branch named `jglick-cache` (ref. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally#modifying-an-inactive-pull-request-locally)
  2. Started with the "jq" download from `publish.sh`, by running the 3 following instructions: https://github.com/jenkins-infra/update-center2/blob/master/site/publish.sh#L7-L10
  3. Initial check of disk space:

```console
~/update_center$ du -sh *
46G     caches
8.0K    CHANGELOG.adoc
153G    download
4.0K    Jenkinsfile
2.9M    jq
12K     pom.xml
16K     README.adoc
464K    resources
100K    site
4.0K    spotbugs-excludes.xml
560K    src
27M     tmp
156K    www2
~/update_center$ df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvdf1      591G  373G  192G  67% /home/jenkins
```

  4. Start the generation only with the command `time ./generate.sh ./www2 ./download`

2022-06-26 11:43 UTC, dduportal commented
So it still fails with the following error stack (tried a 2nd time with the file removed from cache):

```
2022-06-26 11:42:38.239+0000 [id=1]     WARNING i.j.u.w.VersionCappedMavenRepository#listJenkinsPlugins: Failed to filter plugin for plugin: aws-java-sdk-elasticbeanstalk
java.io.FileNotFoundException: caches/artifactory/L3JlbGVhc2VzL29yZy9qZW5raW5zLWNpL3BsdWdpbnMvYXdzLWphdmEtc2RrL2F3cy1qYXZhLXNkay1lbGFzdGljYmVhbnN0YWxrLzEuMTIuMjQ2LTM0OS52OTZiX2JfZjdlYl9hX2MzYy9hd3MtamF2YS1zZGstZWxhc3RpY2JlYW5zdGFsay0xLjEyLjI0Ni0zNDkudjk2Yl9iX2Y3ZWJfYV9jM2MuaHBpIS9NRVRBLUlORi9NQU5JRkVTVC5NRg== (File name too long)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at io.jenkins.update_center.ArtifactoryRepositoryImpl.getFile(ArtifactoryRepositoryImpl.java:248)
        at io.jenkins.update_center.ArtifactoryRepositoryImpl.getFileContent(ArtifactoryRepositoryImpl.java:225)
        at io.jenkins.update_center.ArtifactoryRepositoryImpl.getManifest(ArtifactoryRepositoryImpl.java:212)
        at io.jenkins.update_center.MavenArtifact.getManifest(MavenArtifact.java:124)
        at io.jenkins.update_center.MavenArtifact.getManifestAttributes(MavenArtifact.java:130)
        at io.jenkins.update_center.HPI.getRequiredJenkinsVersion(HPI.java:92)
        at io.jenkins.update_center.wrappers.VersionCappedMavenRepository.listJenkinsPlugins(VersionCappedMavenRepository.java:69)
        at io.jenkins.update_center.json.UpdateCenterRoot.<init>(UpdateCenterRoot.java:54)
        at io.jenkins.update_center.Main.run(Main.java:252)
        at io.jenkins.update_center.Main.run(Main.java:198)
        at io.jenkins.update_center.Main.main(Main.java:172)
Exception in thread "main" java.lang.IllegalStateException: GITHUB_USERNAME and GITHUB_PASSWORD must be set
        at io.jenkins.update_center.GitHubSource.init(GitHubSource.java:40)
        at io.jenkins.update_center.GitHubSource.getInstance(GitHubSource.java:178)
        at io.jenkins.update_center.HPI.getDefaultBranch(HPI.java:632)
        at io.jenkins.update_center.PluginUpdateCenterEntry.getDefaultBranch(PluginUpdateCenterEntry.java:146)
        at com.alibaba.fastjson.serializer.ASMSerializer_4_PluginUpdateCenterEntry.writeDirectNonContext(Unknown Source)
        at com.alibaba.fastjson.serializer.ASMSerializer_4_PluginUpdateCenterEntry.write(Unknown Source)
        at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:271)
        at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:44)
        at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:360)
        at com.alibaba.fastjson.serializer.ASMSerializer_1_UpdateCenterRoot.writeDirectNonContext(Unknown Source)
        at com.alibaba.fastjson.serializer.ASMSerializer_1_UpdateCenterRoot.write(Unknown Source)
        at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:312)
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:687)
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:676)
        at io.jenkins.update_center.json.WithSignature.writeWithSignature(WithSignature.java:64)
        at io.jenkins.update_center.json.WithSignature.encodeWithSignature(WithSignature.java:100)
        at io.jenkins.update_center.Main.run(Main.java:252)
        at io.jenkins.update_center.Main.run(Main.java:198)
        at io.jenkins.update_center.Main.main(Main.java:172)
```

2022-06-26 12:18 UTC, dduportal approved these changes
LGTM!

Test on a copy of the actual cache runs succesfully and show a set of new files in the cache with the new filename pattern using sha256:

```shell
$ find ./caches -mmin -60 -type f -exec ls -l {} +
-rw-rw-r-- 1 jenkins jenkins     1262 Jun 26 12:14  ./caches/artifactory/0174e98664959620177d76c4c56937aadad123e98869268990b854ec02e13b9b
-rw-rw-r-- 1 jenkins jenkins      152 Jun 26 12:04  ./caches/artifactory/0567d40c8b3f3c1529507dc46787fd18a7fbc0729d499641bd13da61a1bcf66e
-rw-rw-r-- 1 jenkins jenkins      125 Jun 26 12:05  ./caches/artifactory/0583761417cee50d5905aef0824eeee6d999b55b74b35a73faf574a067c570e4
-rw-rw-r-- 1 jenkins jenkins     5508 Jun 26 12:05  ./caches/artifactory/160b19068da68d76e53b15d13dba1340fc150efe7d7bb3e419a39b4eac72abfd
-rw-rw-r-- 2 jenkins jenkins 12999718 Jun 26 12:07  ./caches/artifactory/210ebd98ae2afde6fab795d638bdd478d8e42ed3c4b895083105fda5cf0bf752
-rw-rw-r-- 1 jenkins jenkins     1040 Jun 26 12:14  ./caches/artifactory/22293caf1a449f444d3092684ab8284e7ed2efa513f7998620f3f96ad8698c85
-rw-rw-r-- 1 jenkins jenkins      856 Jun 26 12:15  ./caches/artifactory/287ab0994da0b5d02ace592a02f95f7e3aa96adea745109a4162f4cf18503286
-rw-rw-r-- 1 jenkins jenkins     1461 Jun 26 12:15  ./caches/artifactory/2cf03bc7eefb736a1269da1512ae9ac76d444eb5e243779ce586ce3831e3dd89
```

Ping @daniel-beck @timja I'm not sure about the release process for this project

2022-06-26 12:31 UTC, dduportal commented
Additional note: the first build took 5 min 48 to run with the actual copy of the cache.

2022-06-26 14:04 UTC, timja approved these changes

2022-06-26 14:04 UTC, merged

2022-06-26 14:30 UTC, timja commented
> Ping @daniel-beck @timja I'm not sure about the release process for this project

Seems it needs a release run, @daniel-beck is the only person there https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/component-update-center2.yml#L7

Then this line updated:
https://github.com/jenkins-infra/update-center2/blob/46c86aa54b72e473845c45ec2d561e87607c9173/site/generate.sh#L53

2022-06-27 06:03 UTC, daniel-beck commented
Yes. Please understand project first, then merge PRs.