Mark warning as fixed for cloudformation plugin
jenkins-infra/update-center2 pull request #657
Opened 2022-11-12 20:36 UTC by bitle

This CVE was fixed in https://github.com/jenkinsci/jenkins-cloudformation-plugin/pull/58 and released in version [1.4196.v59065a_32f38a](https://github.com/jenkinsci/jenkins-cloudformation-plugin/releases/tag/1.4196.v59065a_32f38a).

2022-11-22 14:39 UTC, daniel-beck requested changes
Haven't had a chance to test yet, but if this is confirmed, this change needs to be applied first.

2022-11-22 14:39 UTC, daniel-beck commented on resources/warnings.json
> +        "pattern": "jenkins-cloudformation-plugin-[0-1][.][0-9]+"
```suggestion
        "lastVersion": "1.2",
        "pattern": "(0|1[.][02])(|[.-].+)"
```

These patterns are for version numbers.

Additionally, version 1.3 was never released: https://repo.jenkins-ci.org/artifactory/releases/org/jenkins-ci/plugins/jenkins-cloudformation-plugin/

2022-11-23 21:43 UTC, daniel-beck approved these changes

2022-11-23 22:07 UTC, merged

2022-12-03 18:04 UTC, bitle commented
Thank you for fixing the values merging, @daniel-beck! I was offline for some time and couldn't make the changes.