Update artifact-ignores.properties to deprecate plugin
jenkins-infra/update-center2 pull request #665
Opened 2022-12-13 04:47 UTC by sn-priya-jagyasi

Update artifact-ignores.properties to deprecate the plugin "lightstep-incident-response-plugin"

2022-12-13 23:33 UTC, daniel-beck requested changes

2022-12-13 23:33 UTC, daniel-beck commented on resources/artifact-ignores.properties
> +AntepediaReporter-CI      # closed-souce plugin; removal confirmed with owner, Guillaume Rousseau
Why this change?

2022-12-13 23:33 UTC, daniel-beck commented on resources/artifact-ignores.properties
> +lightstep-incident-response-plugin
```suggestion
lightstep-incident-response
```

Please also add a URL providing information about the deprecation/removal for users of this plugin, as demonstrated by other entries in this file.

2022-12-14 04:45 UTC, closed without merging

2022-12-14 04:46 UTC, sn-priya-jagyasi commented
not required , created new [PR](https://github.com/jenkins-infra/update-center2/pull/667/)