Mark SECURITY-1002 as fixed starting
jenkins-infra/update-center2 pull request #726
Opened 2023-07-08 13:06 UTC by reda-alaoui

IMO, the security issue has been fixed starting with https://github.com/jenkinsci/sonar-gerrit-plugin/releases/tag/378.vf4646d4df087 .

2023-07-09 10:01 UTC, daniel-beck requested changes

2023-07-09 11:27 UTC, reda-alaoui commented on resources/warnings.json
> +        "pattern": "([1-2]|3[0-7][0-7])\\..*"
Indeed :man_facepalming:

2023-07-12 21:12 UTC, reda-alaoui commented
Hello? :)

2023-07-17 12:18 UTC, Kevin-CB commented
I was able to confirm locally that the vulnerability is fixed by https://github.com/jenkinsci/sonar-gerrit-plugin/commit/f4646d4df0870bd06b76de86309bb38fbd929d54 which got released in v378.vf4646d4df087

2023-07-17 12:19 UTC, Kevin-CB commented
Once this PR is merged, the warning should be removed within a day.

2023-07-17 12:20 UTC, merged

2023-07-17 12:46 UTC, reda-alaoui commented
Thank you !